replicaCount: 1

image:
  repository: ghcr.io/taronatsumi/helpdesk
  tag: "v0.1.0"
  pullPolicy: IfNotPresent

imagePullSecrets: []

service:
  type: ClusterIP
  port: 80

app:
  logPath: ""
  logLevel: "INFO"

postgres:
  image: postgres:15
  user: helpdesk
  password: helpdesk
  db: helpdesk
  port: 5432
  storage: 1Gi

postgresExporter:
  image: prometheuscommunity/postgres-exporter:v0.15.0
  port: 9187

resources: {}
