apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helpdesk.fullname" . }}-app
data:
  DATABASE_URL: postgres://{{ .Values.postgres.user }}:{{ .Values.postgres.password }}@{{ include "helpdesk.fullname" . }}-postgres:{{ .Values.postgres.port }}/{{ .Values.postgres.db }}
  LOG_LEVEL: {{ .Values.app.logLevel | quote }}
  APP_LOG_PATH: {{ .Values.app.logPath | quote }}
